/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppOnboardingRouteRouteImport } from './routes/_app/_onboarding/route'
import { Route as AppWorkspaceSlugRouteRouteImport } from './routes/_app/$workspaceSlug/route'
import { Route as AuthSignUpIndexRouteImport } from './routes/_auth/sign-up/index'
import { Route as AuthSignInIndexRouteImport } from './routes/_auth/sign-in/index'
import { Route as AppWorkspaceSlugSettingsRouteRouteImport } from './routes/_app/$workspaceSlug/settings/route'
import { Route as AppWorkspaceSlugSidebarRouteRouteImport } from './routes/_app/$workspaceSlug/_sidebar/route'
import { Route as AppOnboardingProfileIndexRouteImport } from './routes/_app/_onboarding/profile/index'
import { Route as AppOnboardingCreateWorkspaceIndexRouteImport } from './routes/_app/_onboarding/create-workspace/index'
import { Route as AppWorkspaceSlugSidebarIndexRouteImport } from './routes/_app/$workspaceSlug/_sidebar/index'
import { Route as AppWorkspaceSlugSettingsProfileIndexRouteImport } from './routes/_app/$workspaceSlug/settings/profile/index'
import { Route as AppWorkspaceSlugSettingsIntegrationsIndexRouteImport } from './routes/_app/$workspaceSlug/settings/integrations/index'
import { Route as AppWorkspaceSlugSettingsPreferencesIndexRouteImport } from './routes/_app/$workspaceSlug/settings/_preferences/index'
import { Route as AppWorkspaceSlugSidebarProjectsIndexRouteImport } from './routes/_app/$workspaceSlug/_sidebar/projects/index'
import { Route as AppWorkspaceSlugSettingsIntegrationsProvidersRouteRouteImport } from './routes/_app/$workspaceSlug/settings/integrations/_providers/route'
import { Route as AppWorkspaceSlugSidebarTasksTaskIdIndexRouteImport } from './routes/_app/$workspaceSlug/_sidebar/tasks/$taskId/index'
import { Route as AppWorkspaceSlugSidebarProjectsProjectIdIndexRouteImport } from './routes/_app/$workspaceSlug/_sidebar/projects/$projectId/index'
import { Route as AppWorkspaceSlugSidebarArchiveProjectsIndexRouteImport } from './routes/_app/$workspaceSlug/_sidebar/archive/projects/index'
import { Route as AppWorkspaceSlugSettingsIntegrationsProvidersLinearIndexRouteImport } from './routes/_app/$workspaceSlug/settings/integrations/_providers/linear/index'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppOnboardingRouteRoute = AppOnboardingRouteRouteImport.update({
  id: '/_onboarding',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppWorkspaceSlugRouteRoute = AppWorkspaceSlugRouteRouteImport.update({
  id: '/$workspaceSlug',
  path: '/$workspaceSlug',
  getParentRoute: () => AppRouteRoute,
} as any)
const AuthSignUpIndexRoute = AuthSignUpIndexRouteImport.update({
  id: '/sign-up/',
  path: '/sign-up/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSignInIndexRoute = AuthSignInIndexRouteImport.update({
  id: '/sign-in/',
  path: '/sign-in/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AppWorkspaceSlugSettingsRouteRoute =
  AppWorkspaceSlugSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AppWorkspaceSlugRouteRoute,
  } as any)
const AppWorkspaceSlugSidebarRouteRoute =
  AppWorkspaceSlugSidebarRouteRouteImport.update({
    id: '/_sidebar',
    getParentRoute: () => AppWorkspaceSlugRouteRoute,
  } as any)
const AppOnboardingProfileIndexRoute =
  AppOnboardingProfileIndexRouteImport.update({
    id: '/profile/',
    path: '/profile/',
    getParentRoute: () => AppOnboardingRouteRoute,
  } as any)
const AppOnboardingCreateWorkspaceIndexRoute =
  AppOnboardingCreateWorkspaceIndexRouteImport.update({
    id: '/create-workspace/',
    path: '/create-workspace/',
    getParentRoute: () => AppOnboardingRouteRoute,
  } as any)
const AppWorkspaceSlugSidebarIndexRoute =
  AppWorkspaceSlugSidebarIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppWorkspaceSlugSidebarRouteRoute,
  } as any)
const AppWorkspaceSlugSettingsProfileIndexRoute =
  AppWorkspaceSlugSettingsProfileIndexRouteImport.update({
    id: '/profile/',
    path: '/profile/',
    getParentRoute: () => AppWorkspaceSlugSettingsRouteRoute,
  } as any)
const AppWorkspaceSlugSettingsIntegrationsIndexRoute =
  AppWorkspaceSlugSettingsIntegrationsIndexRouteImport.update({
    id: '/integrations/',
    path: '/integrations/',
    getParentRoute: () => AppWorkspaceSlugSettingsRouteRoute,
  } as any)
const AppWorkspaceSlugSettingsPreferencesIndexRoute =
  AppWorkspaceSlugSettingsPreferencesIndexRouteImport.update({
    id: '/_preferences/',
    path: '/',
    getParentRoute: () => AppWorkspaceSlugSettingsRouteRoute,
  } as any)
const AppWorkspaceSlugSidebarProjectsIndexRoute =
  AppWorkspaceSlugSidebarProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AppWorkspaceSlugSidebarRouteRoute,
  } as any)
const AppWorkspaceSlugSettingsIntegrationsProvidersRouteRoute =
  AppWorkspaceSlugSettingsIntegrationsProvidersRouteRouteImport.update({
    id: '/integrations/_providers',
    path: '/integrations',
    getParentRoute: () => AppWorkspaceSlugSettingsRouteRoute,
  } as any)
const AppWorkspaceSlugSidebarTasksTaskIdIndexRoute =
  AppWorkspaceSlugSidebarTasksTaskIdIndexRouteImport.update({
    id: '/tasks/$taskId/',
    path: '/tasks/$taskId/',
    getParentRoute: () => AppWorkspaceSlugSidebarRouteRoute,
  } as any)
const AppWorkspaceSlugSidebarProjectsProjectIdIndexRoute =
  AppWorkspaceSlugSidebarProjectsProjectIdIndexRouteImport.update({
    id: '/projects/$projectId/',
    path: '/projects/$projectId/',
    getParentRoute: () => AppWorkspaceSlugSidebarRouteRoute,
  } as any)
const AppWorkspaceSlugSidebarArchiveProjectsIndexRoute =
  AppWorkspaceSlugSidebarArchiveProjectsIndexRouteImport.update({
    id: '/archive/projects/',
    path: '/archive/projects/',
    getParentRoute: () => AppWorkspaceSlugSidebarRouteRoute,
  } as any)
const AppWorkspaceSlugSettingsIntegrationsProvidersLinearIndexRoute =
  AppWorkspaceSlugSettingsIntegrationsProvidersLinearIndexRouteImport.update({
    id: '/linear/',
    path: '/linear/',
    getParentRoute: () =>
      AppWorkspaceSlugSettingsIntegrationsProvidersRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/$workspaceSlug': typeof AppWorkspaceSlugRouteRouteWithChildren
  '/$workspaceSlug/settings': typeof AppWorkspaceSlugSettingsRouteRouteWithChildren
  '/sign-in/': typeof AuthSignInIndexRoute
  '/sign-up/': typeof AuthSignUpIndexRoute
  '/$workspaceSlug/': typeof AppWorkspaceSlugSidebarIndexRoute
  '/create-workspace/': typeof AppOnboardingCreateWorkspaceIndexRoute
  '/profile/': typeof AppOnboardingProfileIndexRoute
  '/$workspaceSlug/settings/integrations': typeof AppWorkspaceSlugSettingsIntegrationsProvidersRouteRouteWithChildren
  '/$workspaceSlug/projects/': typeof AppWorkspaceSlugSidebarProjectsIndexRoute
  '/$workspaceSlug/settings/': typeof AppWorkspaceSlugSettingsPreferencesIndexRoute
  '/$workspaceSlug/settings/integrations/': typeof AppWorkspaceSlugSettingsIntegrationsIndexRoute
  '/$workspaceSlug/settings/profile/': typeof AppWorkspaceSlugSettingsProfileIndexRoute
  '/$workspaceSlug/archive/projects/': typeof AppWorkspaceSlugSidebarArchiveProjectsIndexRoute
  '/$workspaceSlug/projects/$projectId/': typeof AppWorkspaceSlugSidebarProjectsProjectIdIndexRoute
  '/$workspaceSlug/tasks/$taskId/': typeof AppWorkspaceSlugSidebarTasksTaskIdIndexRoute
  '/$workspaceSlug/settings/integrations/linear/': typeof AppWorkspaceSlugSettingsIntegrationsProvidersLinearIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/$workspaceSlug': typeof AppWorkspaceSlugSidebarIndexRoute
  '/sign-in': typeof AuthSignInIndexRoute
  '/sign-up': typeof AuthSignUpIndexRoute
  '/create-workspace': typeof AppOnboardingCreateWorkspaceIndexRoute
  '/profile': typeof AppOnboardingProfileIndexRoute
  '/$workspaceSlug/settings/integrations': typeof AppWorkspaceSlugSettingsIntegrationsIndexRoute
  '/$workspaceSlug/projects': typeof AppWorkspaceSlugSidebarProjectsIndexRoute
  '/$workspaceSlug/settings': typeof AppWorkspaceSlugSettingsPreferencesIndexRoute
  '/$workspaceSlug/settings/profile': typeof AppWorkspaceSlugSettingsProfileIndexRoute
  '/$workspaceSlug/archive/projects': typeof AppWorkspaceSlugSidebarArchiveProjectsIndexRoute
  '/$workspaceSlug/projects/$projectId': typeof AppWorkspaceSlugSidebarProjectsProjectIdIndexRoute
  '/$workspaceSlug/tasks/$taskId': typeof AppWorkspaceSlugSidebarTasksTaskIdIndexRoute
  '/$workspaceSlug/settings/integrations/linear': typeof AppWorkspaceSlugSettingsIntegrationsProvidersLinearIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_app/$workspaceSlug': typeof AppWorkspaceSlugRouteRouteWithChildren
  '/_app/_onboarding': typeof AppOnboardingRouteRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/$workspaceSlug/_sidebar': typeof AppWorkspaceSlugSidebarRouteRouteWithChildren
  '/_app/$workspaceSlug/settings': typeof AppWorkspaceSlugSettingsRouteRouteWithChildren
  '/_auth/sign-in/': typeof AuthSignInIndexRoute
  '/_auth/sign-up/': typeof AuthSignUpIndexRoute
  '/_app/$workspaceSlug/_sidebar/': typeof AppWorkspaceSlugSidebarIndexRoute
  '/_app/_onboarding/create-workspace/': typeof AppOnboardingCreateWorkspaceIndexRoute
  '/_app/_onboarding/profile/': typeof AppOnboardingProfileIndexRoute
  '/_app/$workspaceSlug/settings/integrations/_providers': typeof AppWorkspaceSlugSettingsIntegrationsProvidersRouteRouteWithChildren
  '/_app/$workspaceSlug/_sidebar/projects/': typeof AppWorkspaceSlugSidebarProjectsIndexRoute
  '/_app/$workspaceSlug/settings/_preferences/': typeof AppWorkspaceSlugSettingsPreferencesIndexRoute
  '/_app/$workspaceSlug/settings/integrations/': typeof AppWorkspaceSlugSettingsIntegrationsIndexRoute
  '/_app/$workspaceSlug/settings/profile/': typeof AppWorkspaceSlugSettingsProfileIndexRoute
  '/_app/$workspaceSlug/_sidebar/archive/projects/': typeof AppWorkspaceSlugSidebarArchiveProjectsIndexRoute
  '/_app/$workspaceSlug/_sidebar/projects/$projectId/': typeof AppWorkspaceSlugSidebarProjectsProjectIdIndexRoute
  '/_app/$workspaceSlug/_sidebar/tasks/$taskId/': typeof AppWorkspaceSlugSidebarTasksTaskIdIndexRoute
  '/_app/$workspaceSlug/settings/integrations/_providers/linear/': typeof AppWorkspaceSlugSettingsIntegrationsProvidersLinearIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$workspaceSlug'
    | '/$workspaceSlug/settings'
    | '/sign-in/'
    | '/sign-up/'
    | '/$workspaceSlug/'
    | '/create-workspace/'
    | '/profile/'
    | '/$workspaceSlug/settings/integrations'
    | '/$workspaceSlug/projects/'
    | '/$workspaceSlug/settings/'
    | '/$workspaceSlug/settings/integrations/'
    | '/$workspaceSlug/settings/profile/'
    | '/$workspaceSlug/archive/projects/'
    | '/$workspaceSlug/projects/$projectId/'
    | '/$workspaceSlug/tasks/$taskId/'
    | '/$workspaceSlug/settings/integrations/linear/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$workspaceSlug'
    | '/sign-in'
    | '/sign-up'
    | '/create-workspace'
    | '/profile'
    | '/$workspaceSlug/settings/integrations'
    | '/$workspaceSlug/projects'
    | '/$workspaceSlug/settings'
    | '/$workspaceSlug/settings/profile'
    | '/$workspaceSlug/archive/projects'
    | '/$workspaceSlug/projects/$projectId'
    | '/$workspaceSlug/tasks/$taskId'
    | '/$workspaceSlug/settings/integrations/linear'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/_app/$workspaceSlug'
    | '/_app/_onboarding'
    | '/_app/'
    | '/_app/$workspaceSlug/_sidebar'
    | '/_app/$workspaceSlug/settings'
    | '/_auth/sign-in/'
    | '/_auth/sign-up/'
    | '/_app/$workspaceSlug/_sidebar/'
    | '/_app/_onboarding/create-workspace/'
    | '/_app/_onboarding/profile/'
    | '/_app/$workspaceSlug/settings/integrations/_providers'
    | '/_app/$workspaceSlug/_sidebar/projects/'
    | '/_app/$workspaceSlug/settings/_preferences/'
    | '/_app/$workspaceSlug/settings/integrations/'
    | '/_app/$workspaceSlug/settings/profile/'
    | '/_app/$workspaceSlug/_sidebar/archive/projects/'
    | '/_app/$workspaceSlug/_sidebar/projects/$projectId/'
    | '/_app/$workspaceSlug/_sidebar/tasks/$taskId/'
    | '/_app/$workspaceSlug/settings/integrations/_providers/linear/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/_onboarding': {
      id: '/_app/_onboarding'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppOnboardingRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/$workspaceSlug': {
      id: '/_app/$workspaceSlug'
      path: '/$workspaceSlug'
      fullPath: '/$workspaceSlug'
      preLoaderRoute: typeof AppWorkspaceSlugRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_auth/sign-up/': {
      id: '/_auth/sign-up/'
      path: '/sign-up'
      fullPath: '/sign-up/'
      preLoaderRoute: typeof AuthSignUpIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/sign-in/': {
      id: '/_auth/sign-in/'
      path: '/sign-in'
      fullPath: '/sign-in/'
      preLoaderRoute: typeof AuthSignInIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_app/$workspaceSlug/settings': {
      id: '/_app/$workspaceSlug/settings'
      path: '/settings'
      fullPath: '/$workspaceSlug/settings'
      preLoaderRoute: typeof AppWorkspaceSlugSettingsRouteRouteImport
      parentRoute: typeof AppWorkspaceSlugRouteRoute
    }
    '/_app/$workspaceSlug/_sidebar': {
      id: '/_app/$workspaceSlug/_sidebar'
      path: ''
      fullPath: '/$workspaceSlug'
      preLoaderRoute: typeof AppWorkspaceSlugSidebarRouteRouteImport
      parentRoute: typeof AppWorkspaceSlugRouteRoute
    }
    '/_app/_onboarding/profile/': {
      id: '/_app/_onboarding/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof AppOnboardingProfileIndexRouteImport
      parentRoute: typeof AppOnboardingRouteRoute
    }
    '/_app/_onboarding/create-workspace/': {
      id: '/_app/_onboarding/create-workspace/'
      path: '/create-workspace'
      fullPath: '/create-workspace/'
      preLoaderRoute: typeof AppOnboardingCreateWorkspaceIndexRouteImport
      parentRoute: typeof AppOnboardingRouteRoute
    }
    '/_app/$workspaceSlug/_sidebar/': {
      id: '/_app/$workspaceSlug/_sidebar/'
      path: '/'
      fullPath: '/$workspaceSlug/'
      preLoaderRoute: typeof AppWorkspaceSlugSidebarIndexRouteImport
      parentRoute: typeof AppWorkspaceSlugSidebarRouteRoute
    }
    '/_app/$workspaceSlug/settings/profile/': {
      id: '/_app/$workspaceSlug/settings/profile/'
      path: '/profile'
      fullPath: '/$workspaceSlug/settings/profile/'
      preLoaderRoute: typeof AppWorkspaceSlugSettingsProfileIndexRouteImport
      parentRoute: typeof AppWorkspaceSlugSettingsRouteRoute
    }
    '/_app/$workspaceSlug/settings/integrations/': {
      id: '/_app/$workspaceSlug/settings/integrations/'
      path: '/integrations'
      fullPath: '/$workspaceSlug/settings/integrations/'
      preLoaderRoute: typeof AppWorkspaceSlugSettingsIntegrationsIndexRouteImport
      parentRoute: typeof AppWorkspaceSlugSettingsRouteRoute
    }
    '/_app/$workspaceSlug/settings/_preferences/': {
      id: '/_app/$workspaceSlug/settings/_preferences/'
      path: '/'
      fullPath: '/$workspaceSlug/settings/'
      preLoaderRoute: typeof AppWorkspaceSlugSettingsPreferencesIndexRouteImport
      parentRoute: typeof AppWorkspaceSlugSettingsRouteRoute
    }
    '/_app/$workspaceSlug/_sidebar/projects/': {
      id: '/_app/$workspaceSlug/_sidebar/projects/'
      path: '/projects'
      fullPath: '/$workspaceSlug/projects/'
      preLoaderRoute: typeof AppWorkspaceSlugSidebarProjectsIndexRouteImport
      parentRoute: typeof AppWorkspaceSlugSidebarRouteRoute
    }
    '/_app/$workspaceSlug/settings/integrations/_providers': {
      id: '/_app/$workspaceSlug/settings/integrations/_providers'
      path: '/integrations'
      fullPath: '/$workspaceSlug/settings/integrations'
      preLoaderRoute: typeof AppWorkspaceSlugSettingsIntegrationsProvidersRouteRouteImport
      parentRoute: typeof AppWorkspaceSlugSettingsRouteRoute
    }
    '/_app/$workspaceSlug/_sidebar/tasks/$taskId/': {
      id: '/_app/$workspaceSlug/_sidebar/tasks/$taskId/'
      path: '/tasks/$taskId'
      fullPath: '/$workspaceSlug/tasks/$taskId/'
      preLoaderRoute: typeof AppWorkspaceSlugSidebarTasksTaskIdIndexRouteImport
      parentRoute: typeof AppWorkspaceSlugSidebarRouteRoute
    }
    '/_app/$workspaceSlug/_sidebar/projects/$projectId/': {
      id: '/_app/$workspaceSlug/_sidebar/projects/$projectId/'
      path: '/projects/$projectId'
      fullPath: '/$workspaceSlug/projects/$projectId/'
      preLoaderRoute: typeof AppWorkspaceSlugSidebarProjectsProjectIdIndexRouteImport
      parentRoute: typeof AppWorkspaceSlugSidebarRouteRoute
    }
    '/_app/$workspaceSlug/_sidebar/archive/projects/': {
      id: '/_app/$workspaceSlug/_sidebar/archive/projects/'
      path: '/archive/projects'
      fullPath: '/$workspaceSlug/archive/projects/'
      preLoaderRoute: typeof AppWorkspaceSlugSidebarArchiveProjectsIndexRouteImport
      parentRoute: typeof AppWorkspaceSlugSidebarRouteRoute
    }
    '/_app/$workspaceSlug/settings/integrations/_providers/linear/': {
      id: '/_app/$workspaceSlug/settings/integrations/_providers/linear/'
      path: '/linear'
      fullPath: '/$workspaceSlug/settings/integrations/linear/'
      preLoaderRoute: typeof AppWorkspaceSlugSettingsIntegrationsProvidersLinearIndexRouteImport
      parentRoute: typeof AppWorkspaceSlugSettingsIntegrationsProvidersRouteRoute
    }
  }
}

interface AppWorkspaceSlugSidebarRouteRouteChildren {
  AppWorkspaceSlugSidebarIndexRoute: typeof AppWorkspaceSlugSidebarIndexRoute
  AppWorkspaceSlugSidebarProjectsIndexRoute: typeof AppWorkspaceSlugSidebarProjectsIndexRoute
  AppWorkspaceSlugSidebarArchiveProjectsIndexRoute: typeof AppWorkspaceSlugSidebarArchiveProjectsIndexRoute
  AppWorkspaceSlugSidebarProjectsProjectIdIndexRoute: typeof AppWorkspaceSlugSidebarProjectsProjectIdIndexRoute
  AppWorkspaceSlugSidebarTasksTaskIdIndexRoute: typeof AppWorkspaceSlugSidebarTasksTaskIdIndexRoute
}

const AppWorkspaceSlugSidebarRouteRouteChildren: AppWorkspaceSlugSidebarRouteRouteChildren =
  {
    AppWorkspaceSlugSidebarIndexRoute: AppWorkspaceSlugSidebarIndexRoute,
    AppWorkspaceSlugSidebarProjectsIndexRoute:
      AppWorkspaceSlugSidebarProjectsIndexRoute,
    AppWorkspaceSlugSidebarArchiveProjectsIndexRoute:
      AppWorkspaceSlugSidebarArchiveProjectsIndexRoute,
    AppWorkspaceSlugSidebarProjectsProjectIdIndexRoute:
      AppWorkspaceSlugSidebarProjectsProjectIdIndexRoute,
    AppWorkspaceSlugSidebarTasksTaskIdIndexRoute:
      AppWorkspaceSlugSidebarTasksTaskIdIndexRoute,
  }

const AppWorkspaceSlugSidebarRouteRouteWithChildren =
  AppWorkspaceSlugSidebarRouteRoute._addFileChildren(
    AppWorkspaceSlugSidebarRouteRouteChildren,
  )

interface AppWorkspaceSlugSettingsIntegrationsProvidersRouteRouteChildren {
  AppWorkspaceSlugSettingsIntegrationsProvidersLinearIndexRoute: typeof AppWorkspaceSlugSettingsIntegrationsProvidersLinearIndexRoute
}

const AppWorkspaceSlugSettingsIntegrationsProvidersRouteRouteChildren: AppWorkspaceSlugSettingsIntegrationsProvidersRouteRouteChildren =
  {
    AppWorkspaceSlugSettingsIntegrationsProvidersLinearIndexRoute:
      AppWorkspaceSlugSettingsIntegrationsProvidersLinearIndexRoute,
  }

const AppWorkspaceSlugSettingsIntegrationsProvidersRouteRouteWithChildren =
  AppWorkspaceSlugSettingsIntegrationsProvidersRouteRoute._addFileChildren(
    AppWorkspaceSlugSettingsIntegrationsProvidersRouteRouteChildren,
  )

interface AppWorkspaceSlugSettingsRouteRouteChildren {
  AppWorkspaceSlugSettingsIntegrationsProvidersRouteRoute: typeof AppWorkspaceSlugSettingsIntegrationsProvidersRouteRouteWithChildren
  AppWorkspaceSlugSettingsPreferencesIndexRoute: typeof AppWorkspaceSlugSettingsPreferencesIndexRoute
  AppWorkspaceSlugSettingsIntegrationsIndexRoute: typeof AppWorkspaceSlugSettingsIntegrationsIndexRoute
  AppWorkspaceSlugSettingsProfileIndexRoute: typeof AppWorkspaceSlugSettingsProfileIndexRoute
}

const AppWorkspaceSlugSettingsRouteRouteChildren: AppWorkspaceSlugSettingsRouteRouteChildren =
  {
    AppWorkspaceSlugSettingsIntegrationsProvidersRouteRoute:
      AppWorkspaceSlugSettingsIntegrationsProvidersRouteRouteWithChildren,
    AppWorkspaceSlugSettingsPreferencesIndexRoute:
      AppWorkspaceSlugSettingsPreferencesIndexRoute,
    AppWorkspaceSlugSettingsIntegrationsIndexRoute:
      AppWorkspaceSlugSettingsIntegrationsIndexRoute,
    AppWorkspaceSlugSettingsProfileIndexRoute:
      AppWorkspaceSlugSettingsProfileIndexRoute,
  }

const AppWorkspaceSlugSettingsRouteRouteWithChildren =
  AppWorkspaceSlugSettingsRouteRoute._addFileChildren(
    AppWorkspaceSlugSettingsRouteRouteChildren,
  )

interface AppWorkspaceSlugRouteRouteChildren {
  AppWorkspaceSlugSidebarRouteRoute: typeof AppWorkspaceSlugSidebarRouteRouteWithChildren
  AppWorkspaceSlugSettingsRouteRoute: typeof AppWorkspaceSlugSettingsRouteRouteWithChildren
}

const AppWorkspaceSlugRouteRouteChildren: AppWorkspaceSlugRouteRouteChildren = {
  AppWorkspaceSlugSidebarRouteRoute:
    AppWorkspaceSlugSidebarRouteRouteWithChildren,
  AppWorkspaceSlugSettingsRouteRoute:
    AppWorkspaceSlugSettingsRouteRouteWithChildren,
}

const AppWorkspaceSlugRouteRouteWithChildren =
  AppWorkspaceSlugRouteRoute._addFileChildren(
    AppWorkspaceSlugRouteRouteChildren,
  )

interface AppOnboardingRouteRouteChildren {
  AppOnboardingCreateWorkspaceIndexRoute: typeof AppOnboardingCreateWorkspaceIndexRoute
  AppOnboardingProfileIndexRoute: typeof AppOnboardingProfileIndexRoute
}

const AppOnboardingRouteRouteChildren: AppOnboardingRouteRouteChildren = {
  AppOnboardingCreateWorkspaceIndexRoute:
    AppOnboardingCreateWorkspaceIndexRoute,
  AppOnboardingProfileIndexRoute: AppOnboardingProfileIndexRoute,
}

const AppOnboardingRouteRouteWithChildren =
  AppOnboardingRouteRoute._addFileChildren(AppOnboardingRouteRouteChildren)

interface AppRouteRouteChildren {
  AppWorkspaceSlugRouteRoute: typeof AppWorkspaceSlugRouteRouteWithChildren
  AppOnboardingRouteRoute: typeof AppOnboardingRouteRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppWorkspaceSlugRouteRoute: AppWorkspaceSlugRouteRouteWithChildren,
  AppOnboardingRouteRoute: AppOnboardingRouteRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthSignInIndexRoute: typeof AuthSignInIndexRoute
  AuthSignUpIndexRoute: typeof AuthSignUpIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthSignInIndexRoute: AuthSignInIndexRoute,
  AuthSignUpIndexRoute: AuthSignUpIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
