import {
  ArrowDownIcon,
  ArrowLeftIcon,
  ArrowRightIcon,
  ArrowsOutLineHorizontalIcon,
  ArrowsOutLineVerticalIcon,
  ArrowUpIcon,
  BugIcon,
  CalendarDotsIcon,
  CaretDownIcon,
  CaretLeftIcon,
  CaretRightIcon,
  CaretUpDownIcon,
  CaretUpIcon,
  CheckCircleIcon,
  CheckIcon,
  CircleIcon,
  ClockIcon,
  DotsThreeIcon,
  DotsThreeVerticalIcon,
  EnvelopeIcon,
  EyeClosedIcon,
  EyeIcon,
  FadersIcon,
  FolderIcon,
  FolderPlusIcon,
  GearIcon,
  GithubLogoIcon,
  GoogleLogoIcon,
  HouseIcon,
  InfoIcon,
  LinkSimpleIcon,
  MagnifyingGlassIcon,
  MinusIcon,
  MoonIcon,
  PencilSimpleIcon,
  PlugsIcon,
  PlusIcon,
  SealWarningIcon,
  SidebarSimpleIcon,
  SignInIcon,
  SignOutIcon,
  SortAscendingIcon,
  SortDescendingIcon,
  SpinnerBallIcon,
  SunIcon,
  TargetIcon,
  TextBIcon,
  TextHIcon,
  TextHOneIcon,
  TextHThreeIcon,
  TextHTwoIcon,
  TextItalicIcon,
  TextStrikethroughIcon,
  UploadIcon,
  UserIcon,
  UsersFourIcon,
  WallIcon,
  WarningCircleIcon,
  WarningIcon,
  XIcon,
} from "@phosphor-icons/react";

export type { IconProps } from "@phosphor-icons/react";

const Icons = {
  ArrowDown: ArrowDownIcon,
  ArrowLeft: ArrowLeftIcon,
  ArrowRight: ArrowRightIcon,
  ArrowUp: ArrowUpIcon,
  ArrowsOutVertical: ArrowsOutLineVerticalIcon,
  ArrowsOutHorizontal: ArrowsOutLineHorizontalIcon,
  Bold: TextBIcon,
  Bug: BugIcon,
  Calendar: CalendarDotsIcon,
  Check: CheckIcon,
  CheckCircle: CheckCircleIcon,
  ChevronDown: CaretDownIcon,
  ChevronLeft: CaretLeftIcon,
  ChevronRight: CaretRightIcon,
  ChevronUp: CaretUpIcon,
  ChevronsUpDown: CaretUpDownIcon,
  Circle: CircleIcon,
  Clock: ClockIcon,
  DotsThreeHorizontal: DotsThreeIcon,
  DotsThreeVertical: DotsThreeVerticalIcon,
  Edit: PencilSimpleIcon,
  EyeClosed: EyeClosedIcon,
  EyeOpen: EyeIcon,
  Mail: EnvelopeIcon,
  Folder: FolderIcon,
  FolderPlus: FolderPlusIcon,
  Github: GithubLogoIcon,
  Google: GoogleLogoIcon,
  Headings: TextHIcon,
  HeadingOne: TextHOneIcon,
  HeadingTwo: TextHTwoIcon,
  HeadingThree: TextHThreeIcon,
  Home: HouseIcon,
  InfoCircle: InfoIcon,
  Italic: TextItalicIcon,
  Link: LinkSimpleIcon,
  LookingGlass: MagnifyingGlassIcon,
  Recount: WallIcon,
  Minus: MinusIcon,
  Moon: MoonIcon,
  Organization: UsersFourIcon,
  Plugs: PlugsIcon,
  Plus: PlusIcon,
  Search: MagnifyingGlassIcon,
  Settings: GearIcon,
  Sidebar: SidebarSimpleIcon,
  SignIn: SignInIcon,
  SignOut: SignOutIcon,
  Slider: FadersIcon,
  Spinner: SpinnerBallIcon,
  SortAscending: SortAscendingIcon,
  SortDescending: SortDescendingIcon,
  StrikeThrough: TextStrikethroughIcon,
  Sun: SunIcon,
  Target: TargetIcon,
  Upload: UploadIcon,
  User: UserIcon,
  Warning: WarningIcon,
  WarningCircle: WarningCircleIcon,
  WarningSeal: SealWarningIcon,
  X: XIcon,
};

export { Icons };
